<a href="https://colab.research.google.com/github/Nivyasunil/ASSIGNMENT-1/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [28]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [29]:
print(np.__version__)

1.21.6


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [30]:
null_vector=np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [31]:
x=np.array([100,20,34])
print(x.size*x.itemsize)

24


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [32]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [33]:
x=np.zeros(10)
x[4]=1

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [34]:
print(np.arange(10,49))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [35]:
x=np.arange(10,49)
print(x[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [36]:
x=np.arange(9)
x.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [37]:
x=np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [38]:
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [39]:
x=np.random.random((3,3,3))
x

array([[[0.98922513, 0.02573824, 0.62705487],
        [0.71779796, 0.62466871, 0.43076912],
        [0.35960733, 0.5486942 , 0.62361438]],

       [[0.72866745, 0.72130572, 0.85633847],
        [0.29474917, 0.39540431, 0.72552217],
        [0.78430287, 0.89536062, 0.59017704]],

       [[0.89253496, 0.05486946, 0.82153553],
        [0.31409585, 0.88858072, 0.22987283],
        [0.65607111, 0.54855214, 0.69340945]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [40]:
x=np.random.random((10,10))
x
minx=x.min()
maxx=x.max()
print(minx,maxx)

0.012095348878956913 0.998131431590459


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [41]:
x=np.random.random(30)
print(x.mean())

0.48229915503036547


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [42]:
x=np.ones((10,10))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [43]:
x=np.ones((5,5))
x=np.pad(x,pad_width=1,mode='constant',constant_values=0)
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [44]:
not_a_num

NameError: ignored

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [45]:
x=np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [46]:
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [47]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [48]:
x=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [49]:
x=np.random.random((3,3))
xmax,xmin=x.max(),x.min()
x=(x-xmin)/(xmax-xmin)
print(x)

[[0.38833082 0.74856355 0.7644802 ]
 [1.         0.13320627 0.03452517]
 [0.         0.60039879 0.15406334]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [50]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)

1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [51]:
arr_1 = np.random.random((5,3))
arr_2 = np.random.random((3,2))
print(arr_1 @ arr_2)
np.dot(arr_1,arr_2)

[[0.82568148 0.68483438]
 [0.61794226 0.67213641]
 [0.33420525 0.71251777]
 [0.63526    0.37466349]
 [0.72486823 0.76095251]]


array([[0.82568148, 0.68483438],
       [0.61794226, 0.67213641],
       [0.33420525, 0.71251777],
       [0.63526   , 0.37466349],
       [0.72486823, 0.76095251]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [52]:
arr=np.arange(16)
print(arr>=3)
arr[(arr>=3) & (arr<=8)]*=(-1)
print(arr)

[False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [53]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [54]:
Z = arange(10)
Z**Z
Z_2 = 2 << Z >> 2
Z_2
print([bin(2) for z in Z_2])
print([bin(z) for z in 2 << Z_2])
print([bin(z) for z in Z_2])
Z<Z>Z

['0b10', '0b10', '0b10', '0b10', '0b10', '0b10', '0b10', '0b10', '0b10', '0b10']
['0b10', '0b100', '0b1000', '0b100000', '0b1000000000', '0b100000000000000000', '0b1000000000000000000000000000000000', '0b0', '0b0', '0b0']
['0b0', '0b1', '0b10', '0b100', '0b1000', '0b10000', '0b100000', '0b1000000', '0b10000000', '0b100000000']


ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [56]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [57]:

arr = np.random.random((5,5))
print(arr)
arr = np.round(arr,2)
print(arr)


[[0.92705957 0.34897819 0.60280375 0.04394251 0.82174275]
 [0.67302265 0.16421039 0.94445326 0.84351942 0.61684229]
 [0.23463256 0.01998959 0.57861055 0.34251919 0.69110202]
 [0.5037705  0.22926884 0.93270518 0.46406812 0.86793228]
 [0.57345186 0.88182788 0.94418882 0.78701731 0.95421758]]
[[0.93 0.35 0.6  0.04 0.82]
 [0.67 0.16 0.94 0.84 0.62]
 [0.23 0.02 0.58 0.34 0.69]
 [0.5  0.23 0.93 0.46 0.87]
 [0.57 0.88 0.94 0.79 0.95]]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [58]:
x=np.array([1,2,3,4])
y=np.array([2,3,1,9])
print(np.intersect1d(x,y))

[1 2 3]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [59]:
import numpy as np
data=np.random.random(1000).reshape(10,10,10)*np.nan
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [60]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [61]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [62]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [63]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.dot(A,B)

-4.5

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [64]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))

[7. 0. 9. 9. 3. 0. 6. 0. 9. 3.]
[7. 0. 9. 9. 3. 0. 6. 0. 9. 3.]
[7. 0. 9. 9. 3. 0. 6. 0. 9. 3.]
[7 0 9 9 3 0 6 0 9 3]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [65]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [66]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [68]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [67]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.05016557 0.12508002 0.2524049  0.35545322 0.48484184 0.51858656
 0.66892182 0.68423115 0.76357497 0.99857335]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [69]:
import functools as ft
Z = np.arange(10)
#np.add.reduce(Z)
ft.reduce(np.add,Z,0)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [70]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print('*'*60)
print(B)
print('*'*60)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[0 0 0 1 1]
************************************************************
[1 0 0 1 0]
************************************************************
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [71]:
Z = np.zeros(10)
Z.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [72]:
import numpy as np
z= np.random.randint(0,9,(10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
poles = np.c_[r,t]
print(poles)

[[11.3137085   0.78539816]
 [ 1.41421356  0.78539816]
 [ 7.28010989  0.27829966]
 [10.          0.92729522]
 [ 2.23606798  0.46364761]
 [ 7.21110255  0.5880026 ]
 [ 6.          0.        ]
 [10.          0.92729522]
 [10.63014581  0.85196633]
 [ 1.41421356  0.78539816]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [73]:
arr = np.random.random(10)
print(arr)
arr[arr.argmax()] = 0
print(arr)

[0.64708201 0.33967115 0.79403361 0.26809432 0.16573488 0.4422873
 0.77925169 0.8232892  0.33349552 0.83302708]
[0.64708201 0.33967115 0.79403361 0.26809432 0.16573488 0.4422873
 0.77925169 0.8232892  0.33349552 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [74]:
# X = np.random.randint(0,11,(5,5))
# Y = np.random.randint(11,22,(5,5))
# C = 1/(Y-X.T)
# C

Y = np.random.randint(0,11,10)
X = np.random.randint(11,22,10)
#print(Y.reshape(1,10))
Y = np.tile(Y,(10,1))
#print(X)
X  = np.tile(X,(10,1)).T
#print(X)

C = 1/(X - Y)
C

array([[0.07142857, 0.08333333, 0.07142857, 0.125     , 0.07142857,
        0.16666667, 0.07692308, 0.09090909, 0.07692308, 0.07142857],
       [0.09090909, 0.11111111, 0.09090909, 0.2       , 0.09090909,
        0.33333333, 0.1       , 0.125     , 0.1       , 0.09090909],
       [0.06666667, 0.07692308, 0.06666667, 0.11111111, 0.06666667,
        0.14285714, 0.07142857, 0.08333333, 0.07142857, 0.06666667],
       [0.07142857, 0.08333333, 0.07142857, 0.125     , 0.07142857,
        0.16666667, 0.07692308, 0.09090909, 0.07692308, 0.07142857],
       [0.05555556, 0.0625    , 0.05555556, 0.08333333, 0.05555556,
        0.1       , 0.05882353, 0.06666667, 0.05882353, 0.05555556],
       [0.05555556, 0.0625    , 0.05555556, 0.08333333, 0.05555556,
        0.1       , 0.05882353, 0.06666667, 0.05882353, 0.05555556],
       [0.06666667, 0.07692308, 0.06666667, 0.11111111, 0.06666667,
        0.14285714, 0.07142857, 0.08333333, 0.07142857, 0.06666667],
       [0.09090909, 0.11111111, 0.0909090

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [75]:
# X = np.random.randint(0,11,(5,5))
# Y = np.random.randint(11,22,(5,5))
# C = 1/(Y-X.T)
# C

Y = np.random.randint(0,11,10)
X = np.random.randint(11,22,10)
#print(Y.reshape(1,10))
Y = np.tile(Y,(10,1))
#print(X)
X  = np.tile(X,(10,1)).T
#print(X)

C = 1/(X - Y)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [76]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [77]:
#np.set_printoptions(threshold=np.nan)
#Z = np.zeros((int(1e4),int(1e4)))
Z = []
print(Z)

[]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [78]:
arr = np.random.uniform(0,10,10)
scal = 5
arr_1 = np.abs(arr - 5)
ind = arr_1.argmin()
print(arr)
print('*'*60)
print(arr[ind])

[3.10968664 7.16023976 0.50088778 2.24551586 3.21570205 4.46260376
 2.6526541  3.28163516 9.7032393  2.71528367]
************************************************************
4.462603758308923


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [79]:
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [80]:
arr = np.random.random((100,2))
X,Y = np.atleast_2d(arr[:,0],arr[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.53735066 0.6915809  1.00746373 0.49518213 0.59691288
  1.05504337 0.85131491 0.64527745 0.11602216]
 [0.53735066 0.         0.19981267 0.68911006 0.57440415 0.20165472
  0.78340033 0.65861075 0.61352899 0.48445007]
 [0.6915809  0.19981267 0.         0.79717908 0.77313147 0.1275185
  0.90360299 0.81358394 0.80229371 0.65931869]
 [1.00746373 0.68911006 0.79717908 0.         0.61193588 0.87363397
  0.11660387 0.23205735 0.47221028 0.89726668]
 [0.49518213 0.57440415 0.77313147 0.61193588 0.         0.75566284
  0.62137573 0.40338159 0.16045896 0.38156675]
 [0.59691288 0.20165472 0.1275185  0.87363397 0.75566284 0.
  0.97370866 0.8590102  0.80996938 0.58150024]
 [1.05504337 0.78340033 0.90360299 0.11660387 0.62137573 0.97370866
  0.         0.21814923 0.46794302 0.94152347]
 [0.85131491 0.65861075 0.81358394 0.23205735 0.40338159 0.8590102
  0.21814923 0.         0.25045059 0.73616503]
 [0.64527745 0.61352899 0.80229371 0.47221028 0.16045896 0.80996938
  0.46794302 0.2504505

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [81]:
Z = np.arange(10, dtype=np.float32)
Z_1 = Z.astype(np.float32, copy=False)
Z_1[0] = 2
print(Z)

[2. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [83]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [84]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [85]:
sigma,myu = 1.0,0.0

X,Y  = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X**2+Y**2)
G = np.exp(-(D-myu)**2/(2*sigma**2))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [86]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

np.put(Z,11,1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [87]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis = 1,keepdims = True)
#print(Y)
X.mean(axis = 1).reshape(-1,1) == X.mean(axis = 1,keepdims =True)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [88]:
Z = np.random.randint(0,10,(5,5))
print(Z)


# Z_1 = Z
# for ind in range(5):
#     Z_1[:,ind].sort()
#print(Z_1)


print(Z[(-Z)[:,1].argsort()])
print(Z[:,Z[1,:].argsort()])

[[7 5 1 9 5]
 [0 9 1 4 8]
 [2 1 7 6 0]
 [0 0 6 9 2]
 [6 2 8 0 8]]
[[0 9 1 4 8]
 [7 5 1 9 5]
 [6 2 8 0 8]
 [2 1 7 6 0]
 [0 0 6 9 2]]
[[7 1 9 5 5]
 [0 1 4 8 9]
 [2 7 6 0 1]
 [0 6 9 2 0]
 [6 8 0 8 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [89]:
Z = np.random.randint(0,3,(3,10))
Z[:,1] = 0
Z = Z.astype(bool)
print(Z)
print(~Z)
(Z).any(axis = 0)

[[ True False False  True False False  True False  True  True]
 [ True False  True  True  True False  True  True False False]
 [ True False  True False  True False  True  True  True  True]]
[[False  True  True False  True  True False  True False False]
 [False  True False False False  True False False  True  True]
 [False  True False  True False  True False False False False]]


array([ True, False,  True,  True,  True, False,  True,  True,  True,
        True])

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [90]:
arr=np.array([8,7,1,5,3,4])
difarr=np.absolute(arr-2)
index=difarr.argmin()
print(arr[index])
print(index)

1
2


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [91]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [92]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [93]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[3. 3. 4. 5. 2. 4. 2. 3. 1. 3.]
[5. 5. 7. 9. 3. 7. 3. 5. 1. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [94]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [95]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)


w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [96]:
A = np.random.randint(0,10,(3,4,3,4)) 
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[63 59 52 51]
 [53 65 64 50]
 [50 46 60 42]]
[[63 59 52 51]
 [53 65 64 50]
 [50 46 60 42]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [97]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.56958897 0.56467239 0.40683731 0.57725406 0.62590185 0.6009177
 0.40704828 0.34787518 0.45170809 0.42592353]
0    0.569589
1    0.564672
2    0.406837
3    0.577254
4    0.625902
5    0.600918
6    0.407048
7    0.347875
8    0.451708
9    0.425924
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [98]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.60097239, 1.19558244, 0.81877756, 0.94276492, 1.1933624 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [99]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [100]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [101]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [102]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 19) ( 1, 37) ( 3, 43) ( 3, 58) ( 5, 64) ( 5, 67) ( 5, 83) ( 5, 88)
 (18, 43) (18, 59) (18, 61) (18, 99) (19, 37) (19, 54) (19, 74) (37, 39)
 (37, 79) (39, 79) (43, 58) (43, 61) (50, 71) (50, 93) (54, 74) (57, 76)
 (57, 81) (59, 99) (64, 67) (71, 93) (76, 81) (83, 88)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [103]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [104]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [105]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [106]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.89588563, -0.94682924, -0.81516099,  0.97059856, -0.36645247,
        0.64539421,  0.47014261,  0.30798477,  0.35725222,  0.57541535,
        0.12545521, -0.53835247,  0.30312155, -0.51795607, -0.24287837,
        0.02226919, -0.41747896, -0.98004457, -0.089085  ,  0.7190525 ,
        0.61842818,  0.33091242, -0.18517539, -0.32531697, -0.96312782,
        0.9595335 , -0.48418515,  0.29649372, -0.43805504,  0.12405374,
       -0.4122515 ,  0.31309341,  0.32201087, -0.8227968 ,  0.83612163,
        0.64763687, -0.85128412,  0.66695976,  0.97684098,  0.11032313,
       -0.21008657, -0.41256608, -0.46403295, -0.07430634,  0.31711916,
        0.24262629,  0.60218304,  0.33679319, -0.59181606,  0.80995477,
        0.56344013, -0.96018914, -0.85130989, -0.91292606,  0.65967994,
        0.8154737 ,  0.13653963,  0.61990013, -0.27126058, -0.73692587,
       -0.22495074,  0.95136155, -0.82069148, -0.82492034,  0.18032444,
        0.20514166, -0.583371  , -0.83968459,  0.61949153, -0.82

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [107]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[3.60807297 7.21574669 3.70898285 3.75050363 5.09847493 5.16578803
 8.94991641 1.57096252 6.48690783 6.40488111]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [108]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.06665061  3.56209278 16.28020586 10.18112383  6.98312437  2.25547393
   7.3167334   4.4130613   2.80625059  0.40643078]
 [ 9.66077807  2.11602399  4.15582335  2.58381276  6.75578035  0.94948188
   9.37823384  1.67475609 10.69390297  7.13402093]
 [ 4.06968999  5.22322018 14.27489021  4.17239607  3.44570197  4.96475107
  11.84582358  5.88681437  2.97371629  5.41075859]
 [ 1.86955577  0.94683796 11.94253794  9.32775978  3.27318779  1.97757793
   4.06385461  0.12848059  1.3560304   2.06301489]
 [ 7.93222616  2.97803058  9.93032374  0.08613944  1.37497316  3.55403122
  12.24543098  3.50450001  7.52407176  7.74273362]
 [ 1.70036681  3.10059     9.82704038  8.84371511  1.44181209  3.98565589
   2.55032909  2.30021968  0.58699653  2.7913722 ]
 [ 2.43681206  6.96387973  6.63588878  9.03450919  1.02181976  7.78021877
   0.72240941  6.16237837  0.26510533  4.96995603]
 [ 9.00886637  3.95027498 10.21615004  1.04184798  1.45897453  4.6740332
  13.54718345  4.44783724  8.34948285  9.03845821]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [109]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[1 0 2 9 4 0 8 2 5 3]
 [3 8 1 8 3 0 6 5 8 2]
 [4 9 5 8 2 7 1 5 4 1]
 [0 4 2 0 4 7 4 5 3 5]
 [2 8 4 7 0 7 1 8 4 6]
 [2 7 7 7 3 2 0 7 8 5]
 [4 9 5 6 0 1 7 0 4 4]
 [9 0 0 5 5 8 0 8 7 8]
 [2 7 6 9 1 6 9 0 1 5]
 [1 5 6 4 1 9 2 6 0 9]]
[[0 0 0 0 0]
 [0 1 0 2 9]
 [0 3 8 1 8]
 [0 4 9 5 8]
 [0 0 4 2 0]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [110]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)
Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [111]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [112]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [113]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)
Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[3 4 1]
   [1 3 2]
   [4 3 1]]

  [[4 1 2]
   [3 2 3]
   [3 1 2]]

  [[1 2 2]
   [2 3 0]
   [1 2 4]]

  [[2 2 3]
   [3 0 0]
   [2 4 1]]

  [[2 3 3]
   [0 0 0]
   [4 1 1]]

  [[3 3 2]
   [0 0 1]
   [1 1 2]]

  [[3 2 1]
   [0 1 4]
   [1 2 1]]

  [[2 1 1]
   [1 4 2]
   [2 1 4]]]


 [[[1 3 2]
   [4 3 1]
   [0 1 4]]

  [[3 2 3]
   [3 1 2]
   [1 4 1]]

  [[2 3 0]
   [1 2 4]
   [4 1 0]]

  [[3 0 0]
   [2 4 1]
   [1 0 2]]

  [[0 0 0]
   [4 1 1]
   [0 2 1]]

  [[0 0 1]
   [1 1 2]
   [2 1 0]]

  [[0 1 4]
   [1 2 1]
   [1 0 1]]

  [[1 4 2]
   [2 1 4]
   [0 1 4]]]


 [[[4 3 1]
   [0 1 4]
   [4 1 3]]

  [[3 1 2]
   [1 4 1]
   [1 3 0]]

  [[1 2 4]
   [4 1 0]
   [3 0 3]]

  [[2 4 1]
   [1 0 2]
   [0 3 4]]

  [[4 1 1]
   [0 2 1]
   [3 4 0]]

  [[1 1 2]
   [2 1 0]
   [4 0 3]]

  [[1 2 1]
   [1 0 1]
   [0 3 2]]

  [[2 1 4]
   [0 1 4]
   [3 2 0]]]


 [[[0 1 4]
   [4 1 3]
   [0 2 0]]

  [[1 4 1]
   [1 3 0]
   [2 0 2]]

  [[4 1 0]
   [3 0 3]
   [0 2 4]]

  [[1 0 2]
   [0 3 4]
   [2 4 4]]

  [[0 2 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [114]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4  4  8  6  9]
 [ 4  0  1 10  9]
 [ 8  1  0 42 10]
 [ 6 10 42  1 12]
 [ 9  9 10 12  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [115]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [116]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)
Z = np.ones((16,16))
k = 4
windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))
Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [117]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [118]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9996 9997 9998 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [119]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [120]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)\

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [121]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.81 s ± 152 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
127 ms ± 767 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
111 ms ± 4.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [133]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 3 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [132]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 3 1]
 [4 1 0]
 [3 4 3]
 [2 2 4]
 [1 1 4]
 [3 4 4]
 [4 2 1]
 [3 1 3]
 [3 1 3]
 [1 0 1]]
[[4 3 1]
 [4 1 0]
 [3 4 3]
 [2 2 4]
 [1 1 4]
 [3 4 4]
 [4 2 1]
 [3 1 3]
 [3 1 3]
 [1 0 1]]
[[4 3 1]
 [4 1 0]
 [3 4 3]
 [2 2 4]
 [1 1 4]
 [3 4 4]
 [4 2 1]
 [3 1 3]
 [3 1 3]
 [1 0 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [131]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [130]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]
[[0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [129]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.32682252, 0.57922425, 0.05313714, 0.40325904, 0.32419067,
        0.43087747, 0.36001004, 0.65093342, 0.20448674, 0.62962035],
       [0.3940758 , 0.69841656, 0.06407166, 0.48624137, 0.39090238,
        0.5195431 , 0.43409263, 0.78488199, 0.24656586, 0.75918313],
       [0.02422938, 0.04294148, 0.00393939, 0.02989609, 0.02403426,
        0.03194361, 0.02668977, 0.04825772, 0.01515987, 0.04667765],
       [0.41141539, 0.72914734, 0.06689085, 0.5076363 , 0.40810233,
        0.54240333, 0.45319298, 0.81941731, 0.25741491, 0.79258768],
       [0.26207226, 0.46446801, 0.04260958, 0.32336513, 0.25996183,
        0.34551178, 0.28868465, 0.52197013, 0.16397371, 0.50487961],
       [0.3229704 , 0.57239717, 0.05251084, 0.398506  , 0.32036958,
        0.4257989 , 0.35576676, 0.64326115, 0.20207654, 0.62219928],
       [0.14024418, 0.24855334, 0.0228019 , 0.17304417, 0.13911482,
        0.18489563, 0.15448541, 0.27932476, 0.08774816, 0.27017902],
       [0.03084999, 0.05467513, 0.0050158

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [125]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [124]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [128]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.2179241   0.17504527]
